version: '2.3'
services:
    enclustra-bsp:
      volumes:
          - '/opt:/opt'
          - '/home/${USER}:/home/mathworks'
          - '/local:/local'
      image: enclustra-bsp-xilinx:2021.2
      build: 
        context: .
        args:
          PUID: ${DOCKER_UID} 
          PGID: ${GID:-101}
